# Generated by Django 5.2.7 on 2025-10-21 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_student_branch_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='position',
        ),
        migrations.CreateModel(
            name='StudentClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Member', 'Member')], max_length=50)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.club')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.student')),
            ],
        ),
    ]
