# Generated by Django 5.2.7 on 2025-10-21 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_event_reports_tasks_teacherclubadvisory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.student')),
            ],
        ),
    ]
